# -*- coding: utf-8 -*-
directories:
  results: '../results'
  data: '../data'
  stopwords: '../stopwords.txt'
  topics:
  replies:
  special_topics:
  recommendations:
  num_result_dirs:
queue:
  exchange_name: 'recommender'
main:
  save_every: 60  # number of seconds between saves
  delete_every: 30  # number of seconds between deletes
  keep_days: 30
  retry_every: 10
preprocessing:
  min_count: 5      #lower limit of the number of tokens
  min_ratio: 10     #lower threshold for the ratio of token count to distinct token count
  min_punc_frac: 0      #lower threshold for the fraction of punctuation marks
  max_punc_frac: 0.5    #upper threshold for the fraction of punctuation marks
  min_replies: 0
recommendation:
  duplicate_thresh: 0.5
  irrelevant_thresh: 0.05
  max_recoms: 5
  top_num_special: 20
  time_decay_factor: 0.9
special_topics:
  smartirs_scheme: 'ntn'
  keyword_num: 3
general:
  datetime_format: '%Y-%m-%d %H:%M:%S'
  timestamp_factor: 1000



PUNCS              = {'。', '，', '、', '：', ':', ';', '；', '“', '”', ' '}
SINGLES            = {'一', '二', '三', '四', '五', '六', '七', '八', '九', '十',
                       '两', '这', '那', '不', '很', '是', '只', '就', '你', '我', 
                       '他', '她', '它', '啊', '呵', '哈', '哦', '去'}
