paths:
  data: '../data'
  stopwords: '../stopwords.txt'
  topics: '../data/topics'
  replies: '../data/replies'
  special_topics: '../data/special_topics'
  topic_save: '../results/topics'
  special_save: '../results/specials'
message_queue:
  host: '192.168.1.102'
  username: 'rabbitadmin'
  password: 'tgb123_321'
  exchange_name: 'recommender'
main:
  save_every: 60  # number of seconds between saves
  delete_every: 30  # number of seconds between deletes
  keep_days: 30
  retry_every: 10  # number of seconds between message consumption retries
preprocessing:
  min_count: 5      #lower limit of the number of tokens
  min_ratio: 10     #lower threshold for the ratio of token count to distinct token count
  min_punc_frac: 0      #lower threshold for the fraction of punctuation marks
  max_punc_frac: 0.5    #upper threshold for the fraction of punctuation marks
  min_replies: 0
  punctuations:
    - '。'
    - ', '
    - '、'
    - '：'
    - ':'
    - ';'
    - '；'
    - '“'
    - '”'
    - ' '
  singles:
    - '一'
    - '二'
    - '三'
    - '四'
    - '五'
    - '六'
    - '七'
    - '八'
    - '九'
    - '十'
    - '两'
    - '这'
    - '那'
    - '不'
    - '很'
    - '是'
    - '只'
    - '就'
    - '你'
    - '我'
    - '他'
    - '她'
    - '它'
    - '啊'
    - '呵'
    - '哈'
    - '哦'
    - '去'
recommendation:
  duplicate_thresh: 0.5
  irrelevant_thresh: 0.05
  max_stored: 10   # max number of recommendations stored on disk
  max_shown: 5   # max number of recommendations given
  max_stored_special: 40
  max_shown_special: 20
  top_num_special: 20
  time_decay_base: 0.9
special_topics:
  smartirs_scheme: 'ntn'
  num_keywords: 3
miscellaneous:
  datetime_format: '%Y-%m-%d %H:%M:%S'
  timestamp_factor: 1000
  num_topic_files_per_folder: 3000
logging:
  dir: '../logs'
  run_log_name: 'run'
  serve_log_name: 'serve'
  log_level: 20
  handler_levels:
    - 20
    - 30
    - 40
    - 50
  format: '[%(asctime)s] [%(name)-10s] [%(levelname)-8s] -- %(message)s'
  mode: 'w'
